name: Auto Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: sudo docker build -t portfolio .
      - name: Restart docker container
        run: sudo docker compose restart portfolio